### ISSUE TITLE
`man/NCAResult4BE.Rd` 파일의 Format 부분

### ISSUE THREAD

**Issue by shanmdphd** [asancpt/BE#1]
@ksbae 배균섭 교수님,

`man/NCAResult4BE.Rd` 파일의 Format 부분이 

A data frame with 66 observations on the following 7 variables. 으로 수정되어야 할 것 같아서 의견 드립니다.

![image](https://user-images.githubusercontent.com/6946821/188402853-eb8f559d-5c25-4175-9d11-0a2ed1fe43b8.png)

![image](https://user-images.githubusercontent.com/6946821/188403252-4e216ccc-7ae1-4b5b-a7f7-19ebbaac56c0.png)

**Comment by ksbae** [comment]
Thank you!

 

I’ll update at the next version.

 

========================

Kyun-Seop Bae MD PhD

 

Professor

Department of Clinical Pharmacology & Therapeutics, 

Asan Medical Center, University of Ulsan

 

88, Olympic-ro 43-gil, Songpa-gu, Seoul 05505, Korea

 

From: Sungpil Han ***@***.***> 
Sent: Monday, September 5, 2022 5:23 PM
To: asancpt/BE ***@***.***>
Cc: Kyun-Seop Bae ***@***.***>; Assign ***@***.***>
Subject: [asancpt/BE] `man/NCAResult4BE.Rd` 파일의 Format 부분 (Issue #1)

 

@ksbae <https://github.com/ksbae>  배균섭 교수님,

man/NCAResult4BE.Rd 파일의 Format 부분이

A data frame with 66 observations on the following 7 variables. 으로 수정되어야 할 것 같아서 의견 드립니다.

 <https://user-images.githubusercontent.com/6946821/188402853-eb8f559d-5c25-4175-9d11-0a2ed1fe43b8.png>
